language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: W0CAx1wwL5IAYb9Mi1UPBgT37tqnGVEXZqvIwOX5kkB7Dk84K5gf0t/Wrc3iTggzRkwblZ0sM5zRYZZSLY/1HP7LhqE8sqpDhZzotL5WdGGSENFm4TElJBakzGIYpMsTgr60XKSJekNip+PanKXPlZ8WOOnptqzeDWG45ePn6MqfIbKHmm5TMf63tKl2h2FacGS7GLHlxSUf1xUEvEF/ILkHuplqvGj0HnDhre3+MIFYasVSIdTotzzB3MXJjDOl55FKyVhysCRbwhnM9UEtHBovy7ccOOi/XjUhqRzImDvTrIMpxA/XY0PyOMIIyiSTYSfJA+AYDXLZxgFXCaa5M1zUj4U+7JgaPEkYFkBkkZGmOyn7ufSLtPLOIMwCZysvshlnV3h5EjUtvxfryjrx7fpZKzW9OgzZotWzJTESQebRB3/pN6Zelbq9iV4jx1X9EwyZuO2jO1yknOAzfew/3B3fHMQQySi6Mnud8HQyv+8WVXHoO40iiZJbmNnNzfBmmoK7gjrJMe7u2bq0wwvmvF8Ka2FVuXO+jOl3lJ9leVBjD9RTzXPBGzl++JBphM72hGC+/0xRVv4SBhBpRjEjcAT70fKSf93GGFm64MyPy2KThHfohVDy9BvMIqj48kzdSvPIQuKZuW9PCn7fuwolm1WbzafLxJqLnLE5vZwKKuo=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
