language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: iWhE0wOiYzSFYYS/NOX9IJy7PKsZy4Q/I5MWPY1+Gs6P9A2dhsZXXvXpobF4uPbceArZAHIuAAdM7aCl+kwH3HpylVeDe7drTc3KbdCo/mIxOvdNVc1r3KP0LQw/AE6vOENk/gsR0YiOibAcL0pHgUlrx1ykpse7kvtcG4l84P8uuFofkBECuuRggG6Lhk/GpP2haOcxQ9j+hvtl6p/V+IUT2VOCOzL3S3qE4oBL4OS9MzVhU8sqz6NgPM1RZYLFktkR4Bw5x/s1PvVuh083MfRc0C0npT6xxv2ktijNBaN9HAWRgVRcwCzKrlcbbsXhSKBtaQ0nOD5JS4FLriBqep28E2WM+IjxbyXWC+atthsypbUt/SP1M4Yqb9k50p46g6SE2STEW/NOiDlSDxKPVldfu9cyi3HOVKBQSevnX2q7oN6hLEyeEqg0cqOcmC5zxrSV0ftQCXrSGI2pMtnDgsqHK1Ca7f4jNQvbF49vD2yRmA0T187c913mDFIDgbNsT10C8YA3tcM+KbAyKMn3L0mw5RRUXxu9BX7EUFTfkwIRgsy10WIshl1K1yh0m2+zWQrmbBnrZx+A8bGmZiqqIAAtj0JbOyQ/PDLzzBMElXYqiTJS0DfJSRlZ9jCWPs1pNousQ9sfAyqTTKMuW+GnGC4TBE5M86u7rRduePmpIDM=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
