language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: dYGY1mbRxYqIZoqj0CevaYi/ypujTgPMrnZxsK8Po+G4cqELPheYeXXKDEB9GLz7zdwvXxJkxlKHcQuF9j+bvMiu/oCWELMq4AGH5quYoBReGD5Qf2hStKR3PduXDql+4U2hxP0Y37hpX2FBcDyMxMgqcJ9NmbVleflY9zW87suXWOakIZn2TrRC+acvdyM+WYZURsiZXkkioGKxlzXFZL9GhHU7GtS5ld0+O8cjLmO1KoK292pPEAYfgfjgbgVp+HmaIzB0HuzsGJ9Qbj8lJp7SgFt06CLOZZ95aIS9rK4RSPECAJv+VysuPx03vukyy7NqWNP5zOZnLEPSW11jGx9A56rvgocW3wKh7knybWFeeyRCYxsEJ3ufQKiJLjvDkoVvJB+RnVG81AHCiKCjYMk/VU4KcjVQhGDfPXVM+TGb0mz/qzjpr4QpnrSjjFVDnpToDkWmzQM9/qmm968Vi8CpbnsDNl+kfDp4Joww2FJbNx54INFrgb9KzXzVdiuxOhaKPiGAbUZDeE2iPyOm4hONiGxn9ni9WcbQ6S+ZWQM6bVdQMaeAOvgwLBDgZ9Po8dk78pHrHZDTrqCMcHxmXRQAc0owSQK/7kGgg74B9ghL+aYMLlvIZTRmjFHH4jQvBPCdHf2SlZKIUr5BEry6Uxhy4Rr3y27sqh/UGR+YJtU=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
